const URL = {
    ASSETS_BUCKET: 'https://s3-ap-southeast-2.amazonaws.com/com.basicallyfine.public-assets/'
};

const GAME_COLOURS = {
    WHITE: '#FFFFFF',
    WHITE_2: '#828282',
    BLUE: '#1B91FF',
    BLUE_2: '#00529C',
    GREEN: '#00BE4C',
    GREEN_2: '#006328',
    YELLOW: '#FFE600',
    YELLOW_2: '#837704',
    ORANGE: '#FF9922',
    ORANGE_2: '#835804',
    RED: '#FF4A31',
    RED_2: '#973C30',
    PINK: '#FF5FDC',
    PINK_2: '#AB009A',
    PURPLE: '#A107FF',
    PURPLE_2: '#6500B4',
};

const FACTION = {
    ARBOREC: 'ARBOREC',
    ARGENT_FLIGHT: 'ARGENT_FLIGHT',
    BARONY_OF_LETNEV: 'BARONY_OF_LETNEV',
    CLAN_OF_SAAR: 'CLAN_OF_SAAR',
    EMBERS_OF_MUAAT: 'EMBERS_OF_MUAAT',
    EMIRATES_OF_HACAN: 'EMIRATES_OF_HACAN',
    EMPYREAN: 'EMPYREAN',
    FEDERATION_OF_SOL: 'FEDERATION_OF_SOL',
    GHOSTS_OF_CREUSS: 'GHOSTS_OF_CREUSS',
    L1Z1X_MINDNET: 'L1Z1X_MINDNET',
    MAHACT_GENE_SORCERERS: 'MAHACT_GENE_SORCERERS',
    MENTAK_COALITION: 'MENTAK_COALITION',
    NAALU_COLLECTIVE: 'NAALU_COLLECTIVE',
    NAAZ_ROKHA_ALLIANCE: 'NAAZ_ROKHA_ALLIANCE',
    NEKRO_VIRUS: 'NEKRO_VIRUS',
    NOMAD: 'NOMAD',
    SARDAKK_NORR: 'SARDAKK_NORR',
    TITANS_OF_UL: 'TITANS_OF_UL',
    UNIVERSITIES_OF_JOL_NAR: 'UNIVERSITIES_OF_JOL_NAR',
    VUILRAITH_CABAL: 'VUILRAITH_CABAL',
    WINNU: 'WINNU',
    XXCHA_KINGDOM: 'XXCHA_KINGDOM',
    YIN_BROTHERHOOD: 'YIN_BROTHERHOOD',
    YSSARIL_TRIBES: 'YSSARIL_TRIBES',
};

const SYSTEM_TILE_BACK = {
    BLUE: 'BLUE SYSTEM',
    RED: 'RED SYSTEM',
    HS: 'HOME SYSTEM',
    SPECIAL: 'SPECIAL',
};

const TECH_COLOR = {
    RED: 'Warfare',
    BLUE: 'Propulsion',
    GREEN: 'Biotic',
    YELLOW: 'Cybernetic'
};

const PLANET_TRAIT = {
    BLUE: 'Cultural',
    RED: 'Hazardous',
    GREEN: 'Industrial'
};

const ANOMALY = {
    SUPERNOVA: 'Supernova',
    ASTEROID_FIELD: 'Asteroid Field',
    NEBULA: 'Nebula',
    GRAV_RIFT: 'Gravity Rift'
};

const WORMHOLE = {
    A: 'α Wormhole',
    B: 'β Wormhole'
};

const UNIT_TYPE = {
    CARRIER: 'CARRIER',
    CRUISER: 'CRUISER',
    DESTROYER: 'DESTROYER',
    DREADNOUGHT: 'DREADNOUGHT',
    FIGHTER: 'FIGHTER',
    INFANTRY: 'INFANTRY',
    PDS: 'PDS',
    SPACE_DOCK: 'SPACE_DOCK',
    WAR_SUN: 'WAR_SUN',
    FLAGSHIP: 'FLAGSHIP',
    MECH: 'MECH',
};

export {
    URL,
    GAME_COLOURS,
    SYSTEM_TILE_BACK,
    TECH_COLOR,
    FACTION,
    PLANET_TRAIT,
    ANOMALY,
    WORMHOLE,
    UNIT_TYPE,
};
